version: '3.3'

services:
   web:
     depends_on:
       - db
     image: vacancies:latest
     build: .
     ports:
       - "80:80"
     volumes:
       - ./:/var/www
#     environment:
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_USER: api
#       WORDPRESS_DB_PASSWORD: Passw0rd

   db:
     image: mtirsel/mysql-5.1
     ports:
       - "3306:3306"
     volumes:
       - db:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: Passw0rd
       MYSQL_DATABASE: vacancies
       MYSQL_USER: vacancies
       MYSQL_PASSWORD: Passw0rd

volumes:
    db: